# Site settings
title: Travel Blog
email: gzaprolifeart01@yahoo.fr
description: A fun blog about traveling
baseurl: "/travel-blog"

twitter_username: Ydrelagraphics
avatar: "https://pbs.twimg.com/profile_images/624178669272104960/i8yYl2tJ.png" # Set footer avatar
paginate: 3

# Build settings
markdown: kramdown
permalink: /:title

# Default Settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Ydrela Graphics" # Set default author name
      categories: "places"
      layout: "post"
      comments: true
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
